name: RSS Torrent Auto-Release

on:
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    
    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 安装必要的依赖
    - name: Install dependencies
      run: |
        pip install feedparser requests
        sudo apt-get update
        sudo apt-get install -y aria2  # 安装 aria2

    # 运行 RSS 处理脚本（下载 .torrent 文件内容）
    - name: Run RSS Processor
      env:
        RSS_URL: ${{ secrets.RSS_URL }}
      run: |
        python process_rss.py  # 运行 Python 脚本，处理 RSS 下载内容

    # 上传到新 Release
    - name: Upload to new Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if ls ./downloaded_files/* 1> /dev/null 2>&1; then
          # 每个文件创建一个新的 release
          for file in ./downloaded_files/*; do
            filename=$(basename "$file")
            tag_name=$(echo "$filename" | sed 's/[^a-zA-Z0-9._-]/_/g')_$(date +'%Y%m%d%H%M%S')

            # 创建新的 Release，标题为文件名
            gh release create "$tag_name" \
              --title "$filename" \
              --notes "Automated update $(date +'%Y-%m-%d %H:%M')" \
              "$file"

            echo "Uploaded $file as new release: $tag_name"
          done

          # 清理下载的文件
          rm -rf ./downloaded_files
        else
          echo "No new torrents found"
        fi

    # 提交处理过的记录
    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add processed.txt
        git diff --quiet && git diff --staged --quiet || git commit -m "Update processed entries"
        git push
